<?php
function druplash_library_info_alter(&$libraries, $extension) {
    // TODO: we first need to ATTACH the render array to the hook in the template!!!!!
    // https://www.drupal.org/docs/8/creating-custom-modules/adding-stylesheets-css-and-javascript-js-to-a-drupal-8-module
/*
    var_dump(array_keys($libraries));
    var_dump($libraries['druplash']);
    var_dump($extension);
    exit;*/
}

function druplash_page_attachments(array &$page) {
    //var_dump($page['#attached']['html_head']);
    $page['#attached']['html_head'][] = [
        [
            '#tag' => 'script',
            '#value' => 'document.toto = "tata"',
        ],
        'druplash_js',
    ];
    //exit;
}


function druplash_theme($existing, $type, $theme, $path) {
    return ['druplash_renderer' =>
        [
            'variables' => [
                'content' => ''
            ]
        ]
    ];
}
